import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import MerchantHeader from "@/components/refund/MerchantHeader";
import PageShell from "@/components/refund/PageShell";
import { PrimaryButton, SecondaryButton } from "@/components/refund/Buttons";
import VoiceInput from "@/components/refund/VoiceInput";
import useSpeechInput from "@/hooks/useSpeechInput";
import { useRefundSession } from "@/state/RefundSessionContext";
export default function IssueDescriptionPage() {const navigate = useNavigate();const { issueDescription, inputMode, setIssue } = useRefundSession();const [mode, setMode] = useState(inputMode);const [text, setText] = useState(issueDescription);const { listening, start, stop } = useSpeechInput(setText);const valid = text.trim().length > 4;const continueFlow = () => {setIssue(text.trim(), mode);navigate("/prepare");};return <PageShell><MerchantHeader /><button onClick={() => navigate("/")} className="mt-7 flex items-center gap-2 text-sm font-medium text-muted-foreground hidden"><ArrowLeft size={17} />Back</button><section className="pt-10"><h1 className="text-[28px] font-semibold leading-[34px] tracking-[-0.02em] text-foreground">What’s wrong with this item?</h1><p className="mt-2 text-base leading-6 text-muted-foreground">Tell us what happened in your own words.</p><div className="refund-surface mt-8 p-4"><p className="text-[11px] font-semibold uppercase tracking-[0.13em] text-muted-foreground">Your description</p>{mode === "text" ? <textarea autoFocus value={text} onChange={(e) => setText(e.target.value)} placeholder="Describe the issue with your item…" className="mt-3 min-h-36 w-full resize-none bg-transparent text-base leading-relaxed text-foreground outline-none placeholder:text-muted-foreground" /> : <p className={`mt-3 min-h-24 text-base leading-relaxed ${text ? "text-foreground" : "text-muted-foreground"}`}>{text || "Your words will appear here as you speak."}</p>}</div></section>{mode === "voice" ? <VoiceInput listening={listening} onStart={start} onStop={stop} onType={() => setMode("text")} /> : <button onClick={() => setMode("voice")} className="mt-auto pt-8 text-sm font-medium text-primary">Use voice instead</button>}<div className="mt-6 flex gap-3"><SecondaryButton onClick={() => navigate("/")} className="w-28">Back</SecondaryButton><PrimaryButton disabled={!valid} onClick={continueFlow}>Continue</PrimaryButton></div></PageShell>;}